### ISSUE TITLE
Feature Request: Case Insensitivity

### ISSUE THREAD

**Issue by themooleman** [nickclyde/rofi-bluetooth#17]
Hi,

I really enjoy this script but I would love if it weren't case sensitive. I don't see how case sensitivity is of any benefit for this utility and rofi is, by default, case-insensitive. 

Would you be willing to offer the option to disable case sensitivity? 

Thanks

**Comment by joshpetit** [comment]
Yea I would definitely like to see this as well, an option to disable it would be awesome!

**Comment by eterniter06** [comment]
Add the -i flag when using -dmenu to enable case-insensitivity: https://github.com/davatorium/rofi/issues/559

Changing
`rofi_command="rofi -dmenu $* -p"`
to
rofi_command="rofi -dmenu -i $* -p"
will make it case-insensitive

**Comment by themooleman** [comment]
Perfect! Thanks!
